Numpy?

NumPy (short for Numerical Python) is a foundational package for numerical computations in Python. It provides support for arrays (including multidimensional arrays) and an assortment of mathematical functions to operate on these arrays. With NumPy, mathematical and logical operations on arrays can be performed efficiently and easily.

Installation
install numpy using pip

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Numpy Quickstart

Creating an array

NumPy's main object is the homogeneous multidimensional array.

In [3]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


Basic Mathematical Operations

In [4]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Element-wise addition
print(x + y)

# Element-wise subtraction
print(x - y)

# Element-wise multiplication
print(x * y)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


Array creation is one of the fundamental tasks in NumPy. You can create arrays from lists, tuples, or use specialized functions provided by NumPy to generate arrays of zeros, ones, sequences, and random values, among others

In [5]:
import numpy as np

# Create an array from a list
arr_from_list = np.array([1, 2, 3, 4])
print(arr_from_list)

# Create an array from a tuple
arr_from_tuple = np.array((5, 6, 7, 8))
print(arr_from_tuple)


[1 2 3 4]
[5 6 7 8]


Random Values

In [6]:
# Create a 2x2 array of random floats between 0 and 1
random_floats = np.random.rand(2, 2)
print(random_floats)

# Create a 2x2 array of random integers between 1 (inclusive) and 10 (exclusive)
random_ints = np.random.randint(1, 10, size=(2, 2))
print(random_ints)


[[0.06339071 0.94877148]
 [0.92705529 0.62128403]]
[[8 2]
 [5 5]]


Broadcasting :

automates certain operations to make arrays compatible for arithmetic operations. For instance, adding a scalar to an array or adding arrays of different but compatible dimensions

In [9]:
a = np.array([1, 2, 3])
b = 2
print(a * b)  


[2 4 6]


Examples:
Array Broadcasting

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2  
print(result)  


[[2 4 6]
 [5 7 9]]


Copies and Views

When manipulating arrays, data can be either copied or viewed. A view shares the same data, whereas a copy will have its own data

In [8]:
# Using a view
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr[1:4]
view_arr[0] = 99
print(arr)  

# Using a copy
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr[1:4].copy()
copy_arr[0] = 99
print(arr)  


[ 1 99  3  4  5]
[1 2 3 4 5]


Data types

NumPy arrays can store data of a variety of types, such as integers, floats, strings, and complex numbers. You can specify the data type of an array when you create it.

Structured arrays

Structured arrays are a special type of NumPy array that can store data of multiple types in a single column. Structured arrays are very useful for storing and working with heterogeneous data.